### ISSUE TITLE
Suggestions about dataset and datasetloader.

### ISSUE THREAD

**Issue by xpqiu** [fastnlp/fastNLP#92]
1. The dataset class should be enough for all the tasks, I don't understand why its sub-classes exist. Instead, different preprocessing methods can be implemented in dataset class.

2. The datasetloader should return a 'dataset' object consisting of instances. Since the field of instance is related to the raw data format, some codes in dataset.convert() shoud be moved into datasetset loader.

**Comment by FengZiYjun** [comment]
1. The use of DataSet has been expanded. Currently, DataSet = (raw) data loader + preprocessor.  Different sub-classes of DataSet are used in different tasks. We cannot help users to implement all preprocessing methods because we don't know what dataset users will have. Users are responsible for creating such a sub-class to represent his data in a new task.
2. The name of "datasetloader" may be confusing. It returns lists rather than DataSet. We are going to fix it soon.

@choosewhatulike @xuyige

**Comment by xuyige** [comment]
@FengZiYjun explained it well. i agree.

**Comment by xpqiu** [comment]
Maybe we need a face-to-face discussion.

**Comment by xpqiu** [comment]
Preprocess methods should be chosen according to the field type, rather than task type.

**Comment by FengZiYjun** [comment]
improvement in #97
